# Generated by Django 5.2.7 on 2026-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PegawaiDataSementara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.BigIntegerField(verbose_name='ID Pegawai')),
                ('nipPegawai', models.CharField(max_length=255, verbose_name='NIP Pegawai')),
                ('id_opd', models.BigIntegerField(verbose_name='ID OPD')),
                ('id_sub_opd', models.BigIntegerField(verbose_name='ID Sub OPD')),
                ('id_jenis_jabatan', models.BigIntegerField(verbose_name='ID Jenis Jabatan')),
                ('id_jabatan', models.BigIntegerField(verbose_name='ID Jabatan')),
                ('id_jfu_jft', models.BigIntegerField(verbose_name='ID JFU/JFT')),
                ('kodeEselon', models.BigIntegerField(verbose_name='Kode Eselon')),
                ('kodeTugasTambahan', models.BigIntegerField(verbose_name='Kode Tugas Tambahan')),
                ('kodeUnitKerja', models.BigIntegerField(verbose_name='Kode Unit Kerja')),
                ('kodeKedudukanPegawai', models.BigIntegerField(verbose_name='Kode Kedudukan Pegawai')),
                ('data_pegawai', models.JSONField(verbose_name='Data Pegawai (JSON dari API)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Pegawai SIMPEG',
                'verbose_name_plural': 'Data Pegawai SIMPEG',
                'db_table': 'api_simpeg_pegawai',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nipPegawai'], name='api_simpeg__nipPega_484b48_idx'), models.Index(fields=['id_pegawai'], name='api_simpeg__id_pega_c276a1_idx'), models.Index(fields=['id_opd'], name='api_simpeg__id_opd_26237e_idx')],
            },
        ),
    ]
