# Generated by Django 5.2.7 on 2026-04-01 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # IMPORTANT: Rename old table FIRST before creating new model with same table name
        migrations.AlterModelOptions(
            name='pegawaidatasementara',
            options={'ordering': ['-created_at'], 'verbose_name': 'Data Pegawai SIMPEG (Lama)', 'verbose_name_plural': 'Data Pegawai SIMPEG (Lama)'},
        ),
        migrations.RemoveIndex(
            model_name='pegawaidatasementara',
            name='api_simpeg__nipPega_484b48_idx',
        ),
        migrations.RemoveIndex(
            model_name='pegawaidatasementara',
            name='api_simpeg__id_pega_c276a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pegawaidatasementara',
            name='api_simpeg__id_opd_26237e_idx',
        ),
        migrations.AlterModelTable(
            name='pegawaidatasementara',
            table='api_simpeg_pegawai_sementara',
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID Pegawai')),
                ('nip_baru', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='NIP Baru')),
                ('nip_lama', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP Lama')),
                ('nama_pegawai', models.CharField(db_index=True, max_length=255, verbose_name='Nama Pegawai')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.IntegerField(blank=True, null=True, verbose_name='Jenis Kelamin')),
                ('alamat_rumah', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True, verbose_name='No HP')),
                ('id_jabatan', models.BigIntegerField(blank=True, null=True, verbose_name='ID Jabatan')),
                ('nama_jabatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Jabatan')),
                ('masa_kerja_jabatan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Masa Kerja Jabatan')),
                ('id_opd', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID OPD')),
                ('nm_opd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama OPD')),
                ('id_sub_opd', models.BigIntegerField(blank=True, null=True, verbose_name='ID Sub OPD')),
                ('nm_sub_opd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Sub OPD')),
                ('id_golongan', models.BigIntegerField(blank=True, null=True, verbose_name='ID Golongan')),
                ('nama_golongan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Golongan')),
                ('id_pangkat', models.BigIntegerField(blank=True, null=True, verbose_name='ID Pangkat')),
                ('nama_pangkat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pangkat')),
                ('tmt_cpns', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMT CPNS')),
                ('masa_kerja_tahun', models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja (Tahun)')),
                ('masa_kerja_bulan', models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja (Bulan)')),
                ('raw_data', models.JSONField(help_text='Full JSON response dari ESIMPEG API', verbose_name='Raw Data dari API')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Sync')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Data Pegawai ESIMPEG',
                'verbose_name_plural': 'Data Pegawai ESIMPEG',
                'db_table': 'api_simpeg_pegawai',
                'ordering': ['nama_pegawai'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Sync')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('new_records', models.IntegerField(default=0, verbose_name='Records Baru')),
                ('updated_records', models.IntegerField(default=0, verbose_name='Records Diupdate')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durasi (detik)')),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi',
                'verbose_name_plural': 'Log Sinkronisasi',
                'db_table': 'api_simpeg_sync_log',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='synced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='synced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['nip_baru'], name='api_simpeg__nip_bar_0c4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['id_pegawai'], name='api_simpeg__id_pega_c276a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['id_opd'], name='api_simpeg__id_opd_26237e_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['nama_pegawai'], name='api_simpeg__nama_pe_eaa7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['synced_at'], name='api_simpeg__synced__2e7a48_idx'),
        ),
    ]
