# Generated by Django 5.2.7 on 2026-04-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0002_pegawai_synclog_alter_pegawaidatasementara_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=50, unique=True, verbose_name='Sync ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('current_page', models.IntegerField(default=0, verbose_name='Current Page')),
                ('total_pages', models.IntegerField(default=0, verbose_name='Total Pages')),
                ('processed_records', models.IntegerField(default=0, verbose_name='Processed Records')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('new_records', models.IntegerField(default=0, verbose_name='New Records')),
                ('updated_records', models.IntegerField(default=0, verbose_name='Updated Records')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sync Progress',
                'verbose_name_plural': 'Sync Progress',
                'db_table': 'api_simpeg_sync_progress',
                'ordering': ['-started_at'],
            },
        ),
    ]
