# Generated by Django 5.2.7 on 2026-04-02 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0003_syncprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='id_pangkat',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='akhir_kerja_p3k',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Akhir Kerja P3K'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='kode_eselon',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Kode Eselon'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='id_golongan',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID Golongan (dari kodeGolongan)'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['kode_eselon'], name='api_simpeg__kode_es_bc47d7_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['id_golongan'], name='api_simpeg__id_golo_ab320a_idx'),
        ),
    ]
