# Generated by Django 5.2.7 on 2026-04-02 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0004_remove_pegawai_id_pangkat_pegawai_akhir_kerja_p3k_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='is_opd_induk',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is OPD Induk'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='no_urut',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No Urut OPD (A_12)'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['no_urut'], name='api_simpeg__no_urut_a6c6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['is_opd_induk'], name='api_simpeg__is_opd__86bcf1_idx'),
        ),
    ]
