# Generated by Django 5.2.7 on 2026-04-02 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0005_pegawai_is_opd_induk_pegawai_no_urut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pegawai',
            name='api_simpeg__no_urut_a6c6f0_idx',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='no_urut',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_opd_urut',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Urutan OPD (A_12)'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='kategori_pegawai',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Kategori Pegawai (1=CPNS, 2=PNS, 3=P3K)'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['id_opd_urut'], name='api_simpeg__id_opd__e0e23e_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawai',
            index=models.Index(fields=['kategori_pegawai'], name='api_simpeg__kategor_81ac7a_idx'),
        ),
    ]
