# Generated by Django 5.2.7 on 2026-03-10 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True, verbose_name='Kode Survey')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Survey')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Survey',
                'verbose_name_plural': 'Jenis Survey',
                'db_table': 'survey_jenis',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='PertanyaanSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pertanyaan', models.CharField(max_length=50, verbose_name='Kode Pertanyaan')),
                ('pertanyaan', models.TextField(verbose_name='Pertanyaan')),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan')),
                ('bobot', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Bobot')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan', to='survey.jenissurvey')),
            ],
            options={
                'verbose_name': 'Pertanyaan Survey',
                'verbose_name_plural': 'Pertanyaan Survey',
                'db_table': 'survey_pertanyaan',
                'ordering': ['jenis_survey', 'urutan'],
                'unique_together': {('jenis_survey', 'kode_pertanyaan')},
            },
        ),
        migrations.CreateModel(
            name='RespondenSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawaiPenilai', models.BigIntegerField(verbose_name='ID Pegawai Penilai')),
                ('nip_pegawaiPenilai', models.CharField(max_length=255, verbose_name='NIP Penilai')),
                ('id_pegawaiDinilai', models.BigIntegerField(verbose_name='ID Pegawai Dinilai')),
                ('nip_pegawaiDinilai', models.CharField(max_length=255, verbose_name='NIP Dinilai')),
                ('peranPenilai', models.CharField(max_length=100, verbose_name='Peran Penilai')),
                ('statusData', models.CharField(default='draft', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responden Survey',
                'verbose_name_plural': 'Responden Survey',
                'db_table': 'survey_responden',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nip_pegawaiPenilai'], name='survey_resp_nip_peg_772541_idx'), models.Index(fields=['nip_pegawaiDinilai'], name='survey_resp_nip_peg_75f618_idx')],
            },
        ),
        migrations.CreateModel(
            name='JawabanSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nilai (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.pertanyaansurvey')),
                ('responden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='survey.respondensurvey')),
            ],
            options={
                'verbose_name': 'Jawaban Survey',
                'verbose_name_plural': 'Jawaban Survey',
                'db_table': 'survey_jawaban',
                'unique_together': {('responden', 'pertanyaan')},
            },
        ),
    ]
