# Generated by Django 5.2.7 on 2026-03-12 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(max_length=200, verbose_name='Nama Periode')),
                ('tanggal_mulai', models.DateTimeField(verbose_name='Tanggal & Jam Mulai')),
                ('tanggal_selesai', models.DateTimeField(verbose_name='Tanggal & Jam Selesai')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='survey.jenissurvey')),
            ],
            options={
                'verbose_name': 'Periode Survey',
                'verbose_name_plural': 'Periode Survey',
                'db_table': 'survey_periode',
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
