# Generated by Django 5.2.7 on 2026-03-12 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_periodesurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianJPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_dinilai', models.CharField(max_length=255, verbose_name='NIP yang Dinilai')),
                ('nama_dinilai', models.CharField(max_length=255, verbose_name='Nama yang Dinilai')),
                ('jabatan_dinilai', models.CharField(max_length=255, verbose_name='Jabatan yang Dinilai')),
                ('unit_kerja_dinilai', models.CharField(max_length=255, verbose_name='Unit Kerja yang Dinilai')),
                ('nip_penilai', models.CharField(max_length=255, verbose_name='NIP Penilai')),
                ('nama_penilai', models.CharField(max_length=255, verbose_name='Nama Penilai')),
                ('jabatan_penilai', models.CharField(max_length=255, verbose_name='Jabatan Penilai')),
                ('unit_kerja_penilai', models.CharField(max_length=255, verbose_name='Unit Kerja Penilai')),
                ('periode_mulai', models.DateField(verbose_name='Periode Mulai')),
                ('periode_selesai', models.DateField(verbose_name='Periode Selesai')),
                ('kepemimpinan', models.IntegerField(help_text='Kemampuan memimpin dan mengarahkan tim', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kepemimpinan')),
                ('kerjasama', models.IntegerField(help_text='Kemampuan bekerja sama dengan tim', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kerjasama')),
                ('komunikasi', models.IntegerField(help_text='Kemampuan berkomunikasi efektif', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Komunikasi')),
                ('inovasi', models.IntegerField(help_text='Kemampuan berinovasi dan berkreasi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Inovasi')),
                ('integritas', models.IntegerField(help_text='Kejujuran dan konsistensi dalam bertindak', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Integritas')),
                ('orientasi_hasil', models.IntegerField(help_text='Fokus pada pencapaian hasil yang berkualitas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Orientasi Hasil')),
                ('komentar', models.TextField(blank=True, null=True, verbose_name='Komentar')),
                ('saran', models.TextField(blank=True, null=True, verbose_name='Saran Perbaikan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Submit')),
            ],
            options={
                'verbose_name': 'Penilaian JPT',
                'verbose_name_plural': 'Penilaian JPT',
                'db_table': 'penilaian_jpt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nip_dinilai'], name='penilaian_j_nip_din_5a461f_idx'), models.Index(fields=['nip_penilai'], name='penilaian_j_nip_pen_ca9168_idx'), models.Index(fields=['status'], name='penilaian_j_status_e9d7f3_idx')],
            },
        ),
    ]
