# Generated by Django 5.2.7 on 2026-03-13 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_add_penilaian_jpt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_survey', models.CharField(max_length=200, verbose_name='Nama Survey')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('tahun', models.IntegerField(verbose_name='Tahun Survey')),
                ('periode_mulai', models.DateField(verbose_name='Periode Mulai')),
                ('periode_selesai', models.DateField(verbose_name='Periode Selesai')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('show_pegawai_penilai', models.BooleanField(default=False, verbose_name='Tampilkan Data Penilai')),
                ('show_foto_pegawai', models.BooleanField(default=True, verbose_name='Tampilkan Foto Pegawai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konfigurasi Survey',
                'verbose_name_plural': 'Konfigurasi Survey',
                'db_table': 'survey_configuration',
                'ordering': ['-tahun', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAspek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aspek', models.CharField(max_length=200, verbose_name='Nama Aspek')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi/Pertanyaan')),
                ('urutan', models.PositiveIntegerField(verbose_name='Urutan')),
                ('skala_min', models.IntegerField(default=1, verbose_name='Skala Minimum')),
                ('skala_max', models.IntegerField(default=5, verbose_name='Skala Maximum')),
                ('label_min', models.CharField(default='Sangat Kurang', max_length=50, verbose_name='Label Minimum')),
                ('label_max', models.CharField(default='Sangat Baik', max_length=50, verbose_name='Label Maximum')),
                ('is_required', models.BooleanField(default=True, verbose_name='Wajib Diisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('survey_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspek_penilaian', to='survey.surveyconfiguration')),
            ],
            options={
                'verbose_name': 'Aspek Penilaian',
                'verbose_name_plural': 'Aspek Penilaian',
                'db_table': 'survey_aspek',
                'ordering': ['survey_config', 'urutan'],
                'unique_together': {('survey_config', 'urutan')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_penilai', models.CharField(max_length=20, verbose_name='NIP Penilai')),
                ('nama_penilai', models.CharField(max_length=200, verbose_name='Nama Penilai')),
                ('jabatan_penilai', models.CharField(max_length=200, verbose_name='Jabatan Penilai')),
                ('unit_kerja_penilai', models.CharField(max_length=200, verbose_name='Unit Kerja Penilai')),
                ('nip_dinilai', models.CharField(max_length=20, verbose_name='NIP yang Dinilai')),
                ('nama_dinilai', models.CharField(max_length=200, verbose_name='Nama yang Dinilai')),
                ('jabatan_dinilai', models.CharField(max_length=200, verbose_name='Jabatan yang Dinilai')),
                ('unit_kerja_dinilai', models.CharField(max_length=200, verbose_name='Unit Kerja yang Dinilai')),
                ('komentar', models.TextField(blank=True, verbose_name='Komentar')),
                ('saran', models.TextField(blank=True, verbose_name='Saran')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('survey_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.surveyconfiguration')),
            ],
            options={
                'verbose_name': 'Response Survey',
                'verbose_name_plural': 'Response Survey',
                'db_table': 'survey_response',
                'ordering': ['-created_at'],
                'unique_together': {('survey_config', 'nip_penilai', 'nip_dinilai')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nilai')),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='survey.surveyaspek')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_jawaban', to='survey.surveyresponse')),
            ],
            options={
                'verbose_name': 'Detail Response Survey',
                'verbose_name_plural': 'Detail Response Survey',
                'db_table': 'survey_response_detail',
                'unique_together': {('response', 'aspek')},
            },
        ),
    ]
