# Generated by Django 5.2.7 on 2026-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_add_pegawai_riwayat_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pegawairiwayatdata',
            new_name='pegawai_riw_periode_57d486_idx',
            old_name='pegawai_riw_periode_idx',
        ),
        migrations.RenameIndex(
            model_name='pegawairiwayatdata',
            new_name='pegawai_riw_jenis_s_552578_idx',
            old_name='pegawai_riw_jenis_idx',
        ),
        migrations.RenameIndex(
            model_name='pegawairiwayatdata',
            new_name='pegawai_riw_periode_d6ffb5_idx',
            old_name='pegawai_riw_opd_idx',
        ),
        migrations.RenameIndex(
            model_name='pegawairiwayatdata',
            new_name='pegawai_riw_periode_2a2d40_idx',
            old_name='pegawai_riw_eselon_idx',
        ),
        migrations.RenameIndex(
            model_name='pegawairiwayatdata',
            new_name='pegawai_riw_snapsho_f2a5d7_idx',
            old_name='pegawai_riw_snapshot_idx',
        ),
        migrations.AlterField(
            model_name='pertanyaansurvey',
            name='judul',
            field=models.CharField(help_text='Judul singkat aspek penilaian (contoh: Berorientasi Pelayanan)', max_length=200, verbose_name='Judul Aspek'),
        ),
        migrations.AlterField(
            model_name='pertanyaansurvey',
            name='pertanyaan',
            field=models.TextField(blank=True, help_text='Kalimat pertanyaan lengkap (contoh: Sejauh mana pegawai mampu memberikan pelayanan yang baik?)', null=True, verbose_name='Pertanyaan Lengkap'),
        ),
    ]
